<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>SampleApplication</RootNamespace>
    <AssemblyName>SampleApplication</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <UseWindowsForms>true</UseWindowsForms>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <ApplicationIcon>software-update-available.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetSparkle.UI.WinForms.NetFramework\NetSparkle.UI.WinForms.NetFramework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
</Project>
