<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0</TargetFrameworks>

    <IsPackable>false</IsPackable>
  	<IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
  	<PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetSparkle.Tools.AppCastGenerator\NetSparkle.Tools.AppCastGenerator.csproj" />
  </ItemGroup>

</Project>
