<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>NetSparkleUpdater.UI.WinForms</RootNamespace>
    <AssemblyName>NetSparkleUpdater.UI.WinForms</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Nullable>Enable</Nullable>
	<Version>3.1.1-preview20261006001</Version>
	<LangVersion>8.0</LangVersion>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageProjectUrl>https://github.com/NetSparkleUpdater/NetSparkle</PackageProjectUrl>
	<PackageIcon>software-update-available.png</PackageIcon>
	<PackageIconUrl />
	<RepositoryUrl>https://github.com/NetSparkleUpdater/NetSparkle.git</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageReleaseNotes>See https://github.com/NetSparkleUpdater/NetSparkle for all information and to file issues/pull requests for and ask questions about this project.</PackageReleaseNotes>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageId>NetSparkleUpdater.UI.WinForms.NetFramework</PackageId>
	<Authors>Deadpikle</Authors>
	<Company>Deadpikle</Company>
	<Description>NetSparkleUpdater/NetSparkle app updater framework with built-in WinForms UI for .NET Framework 4.6.2+. NetSparkle is a C# .NET software update framework that allows you to easily download installer files and update your C# .NET Framework or .NET Core software. Built-in UIs are available for WinForms, WPF, and Avalonia. You provide, somewhere on the internet, an app cast with software version information along with release notes in Markdown or HTML format. The NetSparkle framework then checks for an update in the background, displays the release notes to the user, and lets users download or skip the software update. The framework can also perform silent downloads so that you can present all of the UI yourself or set up your own silent software update system, as allowed by your software architecture. It was inspired by the Sparkle (https://sparkle-project.org/) project for Cocoa developers and the WinSparkle (https://winsparkle.org/) project (a Win32 port).</Description>
	<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\NetSparkle\ArtWork\software-update-available.png" Pack="true" PackagePath="\" />
	</ItemGroup>
	<PropertyGroup>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\bin\Debug\NetSparkle.UI.WinForms.NetFramework\</OutputPath>
    <DocumentationFile>..\bin\Debug\NetSparkle.UI.WinForms\NetSparkleUpdater.UI.WinForms.NetFramework.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\bin\Release\NetSparkle.UI.WinForms.NetFramework\</OutputPath>
    <DocumentationFile>..\bin\Release\NetSparkle.UI.WinForms\NetSparkleUpdater.UI.WinForms.NetFramework.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetSparkle\NetSparkle.csproj" />
  </ItemGroup>
</Project>